# Generated by Django 2.0.2 on 2018-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis', models.CharField(max_length=9)),
                ('centre_no', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=256)),
                ('wrote_2014', models.PositiveIntegerField()),
                ('passed_2014', models.PositiveIntegerField()),
                ('wrote_2015', models.PositiveIntegerField()),
                ('passed_2015', models.PositiveIntegerField()),
                ('wrote_2016', models.PositiveIntegerField()),
                ('passed_2016', models.PositiveIntegerField()),
            ],
        ),
    ]
