# Generated by Django 2.0.2 on 2018-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrecord',
            name='passed_2014',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='passed_2015',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='passed_2016',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='wrote_2014',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='wrote_2015',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='wrote_2016',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
