# Generated by Django 2.0.2 on 2018-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matric', '0002_auto_20180204_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='centre_no',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
